BlueGardensEESystem/src/main/java/com/netbuilder/entities/Address.java
package com.netbuilder.entities;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "Address")
public class Address {

	private int doorNumber;
	private String houseName;
	private String firstLine;
	private String secondLine;
	private String town;
	private String county;
	private String country;
	private String postalOrZipCode;

	public Address(int door, String first, String second, String town,
			String county, String country, String postcode) {
		doorNumber = door;
		firstLine = first;
		secondLine = second;
		this.town = town;
		this.county = country;
		this.country = country;
		postalOrZipCode = postcode;
	}

	public Address(String house, String first, String second, String town,
			String county, String country, String postcode) {
		houseName = house;
		firstLine = first;
		secondLine = second;
		this.town = town;
		this.county = country;
		this.country = country;
		postalOrZipCode = postcode;
	}

	public void setDoorNumber(int door) {
		doorNumber = door;
	}

	public int getDoorNumber() {
		return doorNumber;
	}

	public void setHouseName(String house) {
		houseName = house;
	}

	public String gethouseName() {
		return houseName;
	}

	public void setFirstLine(String line) {
		firstLine = line;
	}

	public String getFirstLine() {
		return firstLine;
	}

	public void setSecondLine(String line) {
		secondLine = line;
	}

	public String getSecondLine() {
		return secondLine;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getTown() {
		return town;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getCounty() {
		return county;
	}

	public void setCountry(String county) {
		this.country = county;
	}

	public String getCountry() {
		return country;
	}

	public void setPostCode(String post) {
		postalOrZipCode = post;
	}

	public String getPostCode(String post) {
		return postalOrZipCode;
	}
}

BlueGardensEESystem/src/main/java/com/netbuilder/entities/Basket.java
package com.netbuilder.entities;

import java.util.ArrayList;
/**
 * 
 * @author @author abalagel Attributes for the Basket unique customer id from
	 *         customer table list of order lines that each contains a product
	 *         and its required quantity passed from CustomerOrderLine.java
 */
public class Basket {
	private long customerId;
	private ArrayList<CustomerOrderLine> customerOrderLines;
	private int customerOrderID;

	/**
	 * Uses a customer id, the order id and the products they wish to order
	 * @param customerOrderID
	 * @param customerId
	 * @param customerOrderLines
	 */
	public Basket(int customerOrderID, long customerId, ArrayList<CustomerOrderLine> customerOrderLines) {
		this.customerOrderID = customerOrderID;
		this.customerId = customerId;
		this.customerOrderLines = customerOrderLines;
	}

	public int getCustomerOrderID() {
		return customerOrderID;
	}

	public void setCustomerOrderID(int customerOrderID) {
		this.customerOrderID = customerOrderID;
	}

	/**
	 * @author abalagel getters and setters for class variables initialise class
	 */
	public long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public ArrayList<CustomerOrderLine> getCustomerOrderLines() {
		return customerOrderLines;
	}

	public void setCustomerOrderLines(
			ArrayList<CustomerOrderLine> customerOrderLine) {
		this.customerOrderLines = customerOrderLine;
	}

}

BlueGardensEESystem/src/main/java/com/netbuilder/entities/CustomerLogin.java
package com.netbuilder.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.netbuilder.util.LoginUtils;

@Entity
@Table(name = "CustomerLogin")
/**
 * 
 * @author gandrews
 *
 */
public class CustomerLogin {

	@Column(name = "email")
	@NotNull
	private String customerEmail;

	public String getCustomerEmail() {
		return customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	/**
	 * The password a user on the website provides
	 */
	@Column(name = "password", nullable = false)
	@Size(min = 6, max = 25)
	@NotNull
	private byte[] customerPassword;
	/**
	 * The username that is provided on the website
	 */
	@Column(name = "username", nullable = false)
	@Size(min = 6, max = 25)
	@NotNull
	private String customerUsername;

	@OneToOne
	@JoinColumn(name = "customerID", nullable = false)
	@NotNull
	private long customerID;

	@Column(name = "salt", nullable = false)
	@NotNull
	private byte[] salt;

	public byte[] getSalt() {
		return salt;
	}

	public void setSalt(byte[] salt) {
		this.salt = salt;
	}

	public byte[] getCustomerPassword() {
		return customerPassword;
	}

	public void setCustomerPassword(byte[] customerPassword) {
		this.customerPassword = customerPassword;
	}

	public String getCustomerUsername() {
		return customerUsername;
	}

	public void setCustomerUsername(String customerUsername) {
		this.customerUsername = customerUsername;
	}

	public long getCustomerID() {
		return this.customerID;
	}

	/**
	 * Basic constructor containing both username and password
	 * 
	 * @param inUsername
	 * @param inPassword
	 */
	public CustomerLogin(long customerID, String inUsername, String inEmail, String inPassword,
			byte[] inSalt) {
		this.customerEmail = inEmail;
		this.customerID = customerID;
		this.customerUsername = inUsername;
		try {
			this.customerPassword = LoginUtils.hash(inPassword, inSalt);
		} catch (Exception e) {
			System.out.println(e.toString());
		}
		this.salt = inSalt;
	}
}

BlueGardensEESystem/src/main/java/com/netbuilder/entities/Discount.java
package com.netbuilder.entities;

/**
 * 
 * @author GAndrews
 * @author ABalagel
 *
 */
public class Discount {
	/**
	 * A unique reference to this discount
	 */
	private long discountID;
	/**
	 * The amount that the discount gives
	 */
	private double discountLevel;
	/**
	 * the specific product that this discount applies to
	 */
	private long productID;
	/**
	 * The discount type (FLAT/PERCENTAGE)
	 */
	private String discountType;
	
	public String getDiscountType() {
		return discountType;
	}
	public void setDiscountType(String discountType) {
		if(discountType == "FLAT" || discountType=="PERCENTAGE")
		{
			this.discountType = discountType;
		}
		else
		{
			this.discountType = "FLAT";
		}
	}
	public long getDiscountID() {
		return discountID;
	}
	public void setDiscountID(long discountID) {
		this.discountID = discountID;
	}
	public double getDiscountLevel() {
		return discountLevel;
	}
	public void setDiscountLevel(double discountLevel) {
		this.discountLevel = discountLevel;
	}
	public long getProductID() {
		return productID;
	}
	public void setProductID(long productID) {
		this.productID = productID;
	}
	
	public Discount(long inProductID, double inDiscountLevel, String inDiscountType)
	{
		this.productID = inProductID;
		this.discountLevel = inDiscountLevel;
		this.discountType = inDiscountType;
	}
	
}

BlueGardensEESystem/src/main/java/com/netbuilder/entities/Supplier.java
package com.netbuilder.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "Supplier")
@NamedQueries({
		@NamedQuery(name = Supplier.FIND_OUT_BY_NAME, query = "SELECT p FROM Supplier p WHERE p.supplierName = :name"),
		@NamedQuery(name = Supplier.FIND_OUT_BY_ID, query = "SELECT p FROM Supplier p WHERE p.supplierId = :id"), })
public class Supplier {
	public static final String FIND_OUT_BY_NAME = "Supplier.findoutbyname";
	public static final String FIND_OUT_BY_ID = "Supplier.findoutbyid";
	/**
	 * @author lczornyj Create the variables for the supplier
	 */

	@Id
	@Column(name = "supplierId", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@NotNull
	private int supplierId;

	@Column(name = "supplierName", nullable = false, length = 45)
	@NotNull
	@Size(min = 2, max = 45)
	private String supplierName;

	@Column(name = "supplierAddress", nullable = false, length = 145)
	@NotNull
	@Size(min = 2, max = 145)
	private String supplierAddress;

	/**
	 * @author lczornyj Create getters and setters for the variables except ID
	 *         as there is no need to set a ID as it will be automatically
	 *         generated
	 * @return
	 */
	public Supplier() {

	}

	public Supplier(String supplierName, String supplierAddress) {
		this.supplierName = supplierName;
		this.supplierAddress = supplierAddress;
	}

	public String getName() {
		return supplierName;
	}

	public void setName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getAddress() {
		return supplierAddress;
	}

	public void setAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	public int getSupplierId() {
		return supplierId;
	}
}

BlueGardensEESystem/src/main/java/com/netbuilder/entities/WarehouseWorker.java
package com.netbuilder.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "WarehouseWorker")
@NamedQueries({
		@NamedQuery(name = WarehouseWorker.FIND_OUT_BY_NAME, query = "SELECT p FROM WarehouseWorker p WHERE p.workerName = :name"),
		@NamedQuery(name = WarehouseWorker.FIND_OUT_BY_ID, query = "SELECT p FROM WarehouseWorker p WHERE p.workerId = :id"),
		@NamedQuery(name = WarehouseWorker.IS_ASSIGNED, query = "SELECT p FROM WarehouseWorker p WHERE p.isAssigned = :isAssigned") })
public class WarehouseWorker {
	public static final String FIND_OUT_BY_NAME = "WarehouseWorker.findoutbyname";
	public static final String FIND_OUT_BY_ID = "WarehouseWorker.findoutbyid";
	public static final String IS_ASSIGNED = "WarehouseWorker.isassigned";
	/**
	 * @author lczornyj Generate warehouse workers attributes and save the
	 *         variables locally.
	 */

	@Id
	@Column(name = "workerId", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@NotNull
	private int workerId;
	@Column(name = "workerName", nullable = false, length = 45)
	@NotNull
	@Size(min = 2, max = 45)
	private String workerName;
	@Column(name = "workerAddress", nullable = false, length = 145)
	@NotNull
	@Size(min = 2, max = 145)
	private String workerAddress;
	@Column(name = "isAssigned", nullable = false)
	@NotNull
	private boolean isAssigned;
	@Column(name = "isLoggedIn", nullable = false)
	@NotNull
	private boolean isLoggedIn;
	@Column(name = "password", nullable = false)
	@NotNull
	private String password;

	public WarehouseWorker() {

	}

	/**
	 * @author lczornyj create getters and setters for the variables except the
	 *         ID as the ID is never set by a person.
	 * @param
	 * @return
	 */

	public WarehouseWorker(String workerName, String workerAddress,
			boolean isAssigned, boolean isLoggedIn, String password) {
		super();
		this.workerName = workerName;
		this.workerAddress = workerAddress;
		this.isAssigned = isAssigned;
		this.isLoggedIn = isLoggedIn;
		this.password = password;
	}
	
	public WarehouseWorker(int workerId, String workerName,
			String workerAddress, boolean isAssigned, boolean isLoggedIn,
			String password) {
		super();
		this.workerId = workerId;
		this.workerName = workerName;
		this.workerAddress = workerAddress;
		this.isAssigned = isAssigned;
		this.isLoggedIn = isLoggedIn;
		this.password = password;
	}

	public boolean isLoggedIn() {
		return isLoggedIn;
	}

	public void setLoggedIn(boolean isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return workerName;
	}

	public void setName(String workerName) {
		this.workerName = workerName;
	}

	public String getAddress() {
		return workerAddress;
	}

	public void setAddress(String workerAddress) {
		this.workerAddress = workerAddress;
	}

	public int getWorkerId() {
		return workerId;
	}

	public boolean isAssigned() {
		return isAssigned;
	}

	public void setAssigned(boolean isAssigned) {
		this.isAssigned = isAssigned;
	}
}

BlueGardensEESystem/src/main/java/com/netbuilder/controllers/AccountController.java
package com.netbuilder.controllers;

import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;

import com.netbuilder.entities.Customer;
import com.netbuilder.entitymanagers.CustomerLoginManager;
import com.netbuilder.entitymanagers.CustomerManager;
import com.netbuilder.util.LoggedInUser;

/**
 * @author abalagel
 * @author jmander
 *
 */
@ManagedBean(name = "accountController")
@RequestScoped
public class AccountController {
	@Inject
	private CustomerManager customerManager;
	@Inject
	private LoggedInUser loggedInUser;
	@Inject
	private CustomerLoginManager customerLoginManager;
	private String username;
	private String password;
	private String confirmPassword;
	private String errmsg;

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getErrmsg() {
		return errmsg;
	}

	public void setErrmsg(String errormsg) {
		this.errmsg = errormsg;
	}

	private Customer customer;

	public AccountController() {
	}

	public String search() {
		if(loggedInUser.getUsername() == null){
			return "landingPage";
		}
		this.customer = customerManager.findByID(loggedInUser.getUserID());
		this.username = loggedInUser.getUsername();
		return "account";
	}

	public String changePassword() {
		if (password.isEmpty() || confirmPassword.isEmpty()) {
			errmsg = "Please enter a password";
			return "account";
		}
		if (password.matches(confirmPassword)) {
			errmsg = "Password Saved!";
			try {
				customerLoginManager.updateCustomerPassword(
						loggedInUser.getUserID(), password);
			} catch (Exception e) {
				e.printStackTrace();
			}
			return "account";
		}
		errmsg = "Passwords do not match, please try again";
		return "account";
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

BlueGardensEESystem/src/main/java/com/netbuilder/controllers/BasketController.java
package com.netbuilder.controllers;

import java.util.ArrayList;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import com.netbuilder.BlueGardensEESystem.DeliveryStatus;
import com.netbuilder.entities.CustomerOrder;
import com.netbuilder.entities.Product;
import com.netbuilder.entitymanagers.CustomerOrderLineManager;
import com.netbuilder.entitymanagers.CustomerOrderManager;
import com.netbuilder.entitymanagers.ProductManager;
import com.netbuilder.util.SessionBasket;

/**
 * @author jmander
 * **/

@ManagedBean(name="basketController")
@SessionScoped
public class BasketController {

	@Inject
	private SessionBasket sessionBasket;
	@Inject
	private ProductManager productManager;
	@Inject
	private CustomerOrderManager customerOrderManager;
	@Inject
	private CustomerOrderLineManager customerOrderLineManager;
	private DeliveryStatus deliveryStatus;
	private ArrayList<Product> items = new ArrayList<Product>();
	private int quantity;
	
	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public ArrayList<Product> getItems() {
		return items;
	}

	public void setItems(ArrayList<Product> items) {
		this.items = items;
	}

	public BasketController(){
	}
	
	public String addProduct(int productID){
		if(quantity!=0){
			sessionBasket.addToBasket(productID, quantity);
			items.add(productManager.findById(productID));
		}
		quantity = 1;
		return "productCatalog";
	}
	
	public double findTotal()
	{
		double total = Math.round(sessionBasket.getTotal());
		return total;
	}
	
	public void checkoutBasket(){
		for(int i=0; i<sessionBasket.getBasket().getCustomerOrderLines().size(); i++){
			customerOrderLineManager.persistCustomerOrderLine(sessionBasket.getBasket().getCustomerOrderLines().get(i));
		}
		customerOrderManager.persistCustomerOrder(new CustomerOrder(
				sessionBasket.getBasket().getCustomerOrderID(), false, sessionBasket.getBasket().getCustomerOrderID(), "Standard delivery",
				sessionBasket.getBasket().getCustomerId(), 0, deliveryStatus.ORDER_PLACED, findTotal()));
	}

}

BlueGardensEESystem/src/main/java/com/netbuilder/controllers/CheckoutController.java
package com.netbuilder.controllers;

public class CheckoutController {
	/*
	 * Error message that can be returned to the users
	 */
	private String errormsg;

	public String getErrorMessage() {
		return errormsg;
	}

	public void setErrorMessage(String inErrorMessage) {
		errormsg = inErrorMessage;
	}

	public void generateProductList() {

	}

	public void sendToPaypal() {

	}

}

BlueGardensEESystem/src/main/webapp/aboutUs.xhtml
<!DOCTYPE html>
<!-- Outlines the code that the system uses and the template it is based off of -->
<!--  author Anca -->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"      
				xmlns:ui="http://java.sun.com/jsf/facelets"     
				template="templates/template.xhtml"
				xmlns:h="http://java.sun.com/jsf/html" >
	<!-- Defines the title of the page using the header 1 tag -->
	<ui:define name = "pagetitle">
		About Us
	</ui:define>
	<ui:define name="sectiontitle">About Us</ui:define>
	
	
	<!-- Contains the actual content of the page -->
	<ui:define name="body">
	<hr/>
	
	<p>NB Gardens is a traditional catalogue company based in the North-West of England,established since 1875. It sells garden products to its registered customers via phone and mail. NB Gardens specialises in gnomes, gnome accessories and garden ornaments and it prides itself on the speed and quality of its service to its expanding customer base.
	   <br/><br/>
	   NB Gardens employs a “buy now, pay if satisfied” purchase model. The company is renowned for the quality of its products, sourcing its stock from only the finest suppliers.</p>
	
	</ui:define>
</ui:composition>

BlueGardensEESystem/src/main/webapp/checkout.xhtml
<!DOCTYPE html>
<!-- Outlines the code that the system uses and the template it is based off of -->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"      
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:h="http://java.sun.com/jsf/html"
				xmlns:f="http://java.sun.com/jsf/core"     
				template="templates/template.xhtml">
	<!-- Defines the title of the page using the header 1 tag -->
	<ui:define name = "pagetitle">
		NBGardens: Checkout
	</ui:define>
	<!-- Defines the title displayed on the page -->
	<ui:define name="sectiontitle">
	Order Placed
	<h3>Your order is ready to be processed, please contact customer services to continue with your order</h3>
	</ui:define>
	<!-- Contains the actual content of the page -->
	<ui:define name="body">
	#{basketController.checkoutBasket()}
		<br/>
		<p>
		Total Price: £ #{basketController.findTotal()}
		</p>
		
		<br/>
		<div id="checkout">
			<!-- DISPLAY BASKET ITEMS -->
						<h:dataTable class="basketTable" value="#{basketController.items}" var="item" border="0">
							<f:facet name="header">
							</f:facet>
								<h:column>
								</h:column>
							<h:column class="basketTableColumn">
								<f:facet name="header">
									<h:outputText value="Product"/>
								</f:facet>
								<h:outputText value="#{item.productName}"/>
							</h:column>
							
							<h:column>
								<f:facet name="header">
									<h:outputText value="Price Per Item"/>
								</f:facet>
								<h:outputText value="#{item.price}"/>
							</h:column>
						</h:dataTable>
		</div>
		<br/><br/>
		<h:button value="See all orders" outcome="tracking" />
		
	</ui:define>
</ui:composition>

BlueGardensEESystem/src/main/webapp/contactUs.xhtml
<!DOCTYPE html>
<!-- Outlines the code that the system uses and the template it is based off of -->
<!--  author Anca -->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
				xmlns:h="http://java.sun.com/jsf/html"
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:t="http://myfaces.apache.org/tomahawk"
				template="templates/template.xhtml"
				xmlns:f="http://java.sun.com/jsf/core">
	<!-- Defines the title of the page using the header 1 tag -->
	<ui:define name = "pagetitle">
		Contact Us
	</ui:define>
	
	<ui:define name="sectiontitle">Contact Us</ui:define>
	
	
	<!-- Defines the title displayed on the page -->
	<!-- <ui:define name="sectiontitle">  -->
		
	<!-- </ui:define>  -->
	
	<!-- Contains the actual content of the page -->
	<ui:define name="body">
	<hr/>
	<div>	
		<h:form>			
			<h:panelGrid>
				<h:outputLabel value="#{contactController.errorMessage}"/><br/>
				<h:outputLabel value="Name" for="customername"/><br/>
				<h:inputText id="customername" value="#{contactFormDetails.name}" maxlength="45" size="20"/><br/>
				<br/>
				<h:outputLabel value="Email" for="customeremail"/><br/>
				<h:inputText id="customeremail" value="#{contactFormDetails.email}" maxlength="45" size="20"/><br/>
				<br/>
				<h:outputLabel value="Message" for="customermessage"/><br/>
				<h:inputTextarea id="customermessage" value="#{contactFormDetails.message}" maxlength="80" width="50%" height="70%"/><br/>
				<h:commandButton action="#{contactController.sendMessage}" value="Send" />
			</h:panelGrid>
		</h:form>
	</div>
	</ui:define>
</ui:composition>

BlueGardensEESystem/src/main/webapp/customerRegistration.xhtml
<!-- author jmander -->
<!DOCTYPE html>
<ui:composition	xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:h="http://java.sun.com/jsf/html"
		template="templates/template.xhtml"
		xmlns:f="http://java.sun.com/jsf/core">			
<ui:define name="pagetitle">Customer Registration</ui:define>

<ui:define name="body">
			<div class="leftTitle">Customer Registration</div>
			<div id="customerRegistration">
				<h:form>
					<h:panelGrid>
						<h:outputLabel value="#{customerRegistrationController.errormsg}"/><br/>
						<h:outputLabel value="First Name" for="customerfirstname"/>
						<h:inputText id="customerfirstname" value="#{customerRegistrationController.firstName}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Last Name" for="customerlastname"/>
						<h:inputText id="customerlastname" value="#{customerRegistrationController.lastName}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Username" for="customerusername"/>
						<h:inputText id="customerusername" value="#{customerRegistrationController.username}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Password" for="customerpassword"/>
						<h:inputSecret id="customerpassword" value="#{customerRegistrationController.password}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Confirm Password" for="customerconfirmpassword"/>
						<h:inputSecret id="customerconfirmpassword" value="#{customerRegistrationController.confirmPassword}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Email" for="customeremail"/>
						<h:inputText id="customeremail" value="#{customerRegistrationController.email}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Confirm Email" for="customerconfirmemail"/>
						<h:inputText id="customerconfirmemail" value="#{customerRegistrationController.confirmEmail}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Address" for="customeraddress"/>
						<h:inputText id="customeraddress" value="#{customerRegistrationController.address}" maxlength="45" size="20"/>
						<br/>
						<h:outputLabel value="Contact Number" for="customercontactnumber"/>
						<h:inputText id="customercontactnumber" value="#{customerRegistrationController.contactNumber}" maxlength="45" size="20"/>
						<br/>
							<h:commandButton action="#{customerRegistrationController.registeredCustomer}" value="Register" />
					</h:panelGrid>
				</h:form>
			</div>
</ui:define>
</ui:composition>

BlueGardensEESystem/src/main/webapp/productPage.xhtml
<!-- @Author JThomas -->
<!-- @Author JMander -->
<!-- @Author GAndrews -->
<!DOCTYPE xhtml>
<!-- Outlines the code that the system uses and the template it is based off of -->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"      
				xmlns:ui="http://java.sun.com/jsf/facelets"  
				xmlns:h="http://java.sun.com/jsf/html"   
				template="templates/template.xhtml">
	<!-- Defines the title of the page using the header 1 tag -->
	<ui:define name = "pagetitle">Product</ui:define>
	<!-- Defines the title displayed on the page -->
	<ui:define name="sectiontitle">
		#{productController.getProductByID()}
		#{productController.product.productName}
	</ui:define>
	
	<!-- Contains the actual content of the page -->
	<ui:define name="body">
	<hr/>
	<div>
	<img src="#{productController.product.imageLink}" alt="#{productController.product.productName}"/><br/><br/>
		#{productController.product.productName}<br/><br/>
		£ #{productController.product.price}<br/><br/>
		Remaining stock: #{productController.product.stockLevel}<br/><br/>
		<ul>
		<li>#{productController.product.featureOne}</li>
		<li>#{productController.product.featureTwo}</li>
		<li>#{productController.product.featureThree}</li>
		<li>#{productController.product.featureFour}</li>
		<li>#{productController.product.featureFive}</li>
		</ul>
		<br/>			
		<h:form rendered="#{loginController.loggedIn == true}">
			<h:panelGrid>
			<h:outputLabel  value="Quantity: " for="quantity"/>
			<h:inputText id="quantity" value="#{basketController.quantity}" maxlength="3" size="20"/><br/>
			<h:commandButton rendered="#{loginController.loggedIn == true}" action="#{basketController.addProduct(productController.product.getProductID())}" value="Add To Basket" /><br/>
			<h:commandButton rendered="#{loginController.loggedIn == true}" action="#{wishlistController.addProduct(productController.product.getProductID())}" value="Add to Wishlist" />
		</h:panelGrid>	
		</h:form>
		</div>
	</ui:define>
</ui:composition>